"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const HauntedHouse_js_1 = __importDefault(require("./quest/HauntedHouse.js"));
const Academy_js_1 = __importDefault(require("./buildings/Academy.js"));
const Contest_js_1 = __importDefault(require("./quest/Contest.js"));
const Bounty_js_1 = __importDefault(require("./quest/Bounty.js"));
const Heist_js_1 = __importDefault(require("./quest/Heist.js"));
const Prison_1 = __importDefault(require("./buildings/Prison"));
console.log('=========> ACADEMY <=========');
console.log(new Academy_js_1.default('Boople Academy'));
console.log(new Academy_js_1.default('Silver Sails School'));
console.log(new Academy_js_1.default('Eyes Wide College'));
console.log('=========> PRISON <=========');
console.log(new Prison_1.default('Boople Prison'));
console.log(new Prison_1.default('Silver Sails Prison'));
console.log(new Prison_1.default('Eyes Wide Prison'));
console.log('=========> CONTEST <=========');
console.log(new Contest_js_1.default('Spanakopita'));
console.log(new Contest_js_1.default('Birthday'));
console.log(new Contest_js_1.default('Olympics'));
console.log('=========> BOUNTIES <=========');
console.log(new Bounty_js_1.default('Rudie Jung'));
console.log(new Bounty_js_1.default('Terry Blast'));
console.log(new Bounty_js_1.default('Megan Billy'));
console.log('=========> HEISTS <=========');
console.log(new Heist_js_1.default());
console.log(new Heist_js_1.default());
console.log(new Heist_js_1.default());
console.log('=========> HAUNTED HOUSES <=========');
console.log(new HauntedHouse_js_1.default());
console.log(new HauntedHouse_js_1.default());
console.log(new HauntedHouse_js_1.default());
